INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, BOOKABLE_STATUS) VALUES (1, 1, 'Red', 'Y');
INSERT INTO LOCATION (LOCATION_ID, LOCATION_NAME, LOCATION_TZ) VALUES (1, 'NYC', 'America/New_York');
INSERT INTO LOCATION (LOCATION_ID, LOCATION_NAME, LOCATION_TZ) VALUES (2, 'LON', 'Europe/London');
