INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON) VALUES (1001, 1, 'Dev Red', '0', '');
INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON) VALUES (1002, 1, 'Dev Blue', '0', '');
INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON) VALUES (1003, 1, 'Dev White', '0', '');
INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON) VALUES (1004, 1, 'Dev Black', '0', '');
INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON) VALUES (1005, 2, 'Dev Elizabeth Conference', '0', '');
INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON) VALUES (1006, 2, 'Dev Thames Planning', '0', '');
INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON) VALUES (1007, 2, 'Dev Very Splendid', '0', '');
INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON) VALUES (1008, 2, 'Dev Tower of London Spooky', '0', '');
INSERT INTO BOOKING (BOOKING_ID, BOOKABLE_ID, SUBJECT, START_DATE, END_DATE) VALUES (1, 1001, 'My Booking', {fn TIMESTAMPADD( SQL_TSI_HOUR, -24, CURRENT_TIMESTAMP)}, {fn TIMESTAMPADD( SQL_TSI_HOUR, -23, CURRENT_TIMESTAMP)});
INSERT INTO BOOKING (BOOKING_ID, BOOKABLE_ID, SUBJECT, START_DATE, END_DATE) VALUES (2, 1001, 'Another Booking', {fn TIMESTAMPADD( SQL_TSI_HOUR, 1, CURRENT_TIMESTAMP)}, {fn TIMESTAMPADD( SQL_TSI_HOUR, 2, CURRENT_TIMESTAMP)});
INSERT INTO BOOKING (BOOKING_ID, BOOKABLE_ID, SUBJECT, START_DATE, END_DATE) VALUES (3, 1002, 'Plan All Things', {fn TIMESTAMPADD( SQL_TSI_HOUR, 3, CURRENT_TIMESTAMP)}, {fn TIMESTAMPADD( SQL_TSI_HOUR, 4, CURRENT_TIMESTAMP)});
INSERT INTO BOOKING (BOOKING_ID, BOOKABLE_ID, SUBJECT, START_DATE, END_DATE) VALUES (4, 1002, 'Execute Proletariat', {fn TIMESTAMPADD( SQL_TSI_HOUR, 7, CURRENT_TIMESTAMP)}, {fn TIMESTAMPADD( SQL_TSI_HOUR, 8, CURRENT_TIMESTAMP)});
INSERT INTO BOOKING (BOOKING_ID, BOOKABLE_ID, SUBJECT, START_DATE, END_DATE) VALUES (5, 1003, 'Wash Hands', {fn TIMESTAMPADD( SQL_TSI_HOUR, 24, CURRENT_TIMESTAMP)}, {fn TIMESTAMPADD( SQL_TSI_HOUR, 25, CURRENT_TIMESTAMP)});

