INSERT INTO LOCATION (ID, NAME, TIME_ZONE) VALUES (1, 'NYC', 'America/New_York');
INSERT INTO LOCATION (ID, NAME, TIME_ZONE) VALUES (2, 'LON', 'Europe/London');

INSERT INTO BOOKABLE (ID, LOCATION_ID, NAME, CLOSED, REASON)
VALUES (1, 1, 'Red', FALSE, '');

