INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON)
VALUES (1, 1, 'Red Room', '0', '');
INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON)
VALUES (2, 1, 'Black Room', '0', '');
INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON)
VALUES (3, 1, 'Blue Room', '0', '');
INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON)
VALUES (4, 1, 'Green Room', '0', '');
INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON)
VALUES (5, 1, 'White Room', '0', '');
INSERT INTO BOOKABLE (BOOKABLE_ID, LOCATION_ID, BOOKABLE_NAME, DISPOSITION_CLOSED, DISPOSITION_REASON)
VALUES (6, 1, 'Yellow Room', '1', 'Closed for remodeling');

INSERT INTO LOCATION (LOCATION_ID, LOCATION_NAME, LOCATION_TZ) VALUES (1, 'NYC', 'America/New_York');
INSERT INTO LOCATION (LOCATION_ID, LOCATION_NAME, LOCATION_TZ) VALUES (2, 'LON', 'Europe/London');
