DROP TABLE IF EXISTS BOOKABLE;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS BOOKING;

CREATE TABLE BOOKABLE (
    BOOKABLE_ID        VARCHAR(36) NOT NULL,
    LOCATION_ID        VARCHAR(36) NOT NULL,
    BOOKABLE_NAME      VARCHAR(50) NOT NULL,
    DISPOSITION_CLOSED CHAR(1)     NOT NULL,
    DISPOSITION_REASON VARCHAR(50) NOT NULL
);

CREATE TABLE LOCATION (
    LOCATION_ID   VARCHAR(36) NOT NULL,
    LOCATION_NAME VARCHAR(50) NOT NULL,
    LOCATION_TZ   VARCHAR(50) NOT NULL
);

CREATE TABLE BOOKING (
    BOOKING_ID  VARCHAR(36)  NOT NULL,
    BOOKABLE_ID VARCHAR(36)  NOT NULL,
    SUBJECT     VARCHAR(255) NOT NULL,
    START_DATE  DATETIME     NOT NULL,
    END_DATE    DATETIME     NOT NULL
);


