DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS bookable;
DROP TABLE IF EXISTS location;

CREATE TABLE user (
    USER_ID            VARCHAR(36) NOT NULL,
    PRIMARY KEY        (USER_ID),
    EXTERNAL_USER_ID   VARCHAR(128) NOT NULL,
    GIVEN_NAME         VARCHAR(128),
    FAMILY_NAME        VARCHAR(128)
);
CREATE INDEX IDX_EXTERNAL_USER_ID
    ON USER (EXTERNAL_USER_ID);

CREATE TABLE bookable (
    ID                 VARCHAR(36) NOT NULL,
    PRIMARY KEY        (ID),
    LOCATION_ID        VARCHAR(36) NOT NULL,
    NAME               VARCHAR(50) NOT NULL,
    CLOSED             BOOLEAN     NOT NULL,
    REASON             VARCHAR(50) NOT NULL
);
CREATE INDEX IDX_LOCATION_ID
    ON BOOKABLE (LOCATION_ID);

CREATE TABLE location (
    ID                 VARCHAR(36) NOT NULL,
    PRIMARY KEY        (ID),
    NAME               VARCHAR(50) NOT NULL,
    TIME_ZONE          VARCHAR(50) NOT NULL
);

CREATE TABLE booking (
    BOOKING_ID         VARCHAR(36)  NOT NULL,
    PRIMARY KEY        (BOOKING_ID),
    BOOKABLE_ID        VARCHAR(36)  NOT NULL,
    SUBJECT            VARCHAR(255) NOT NULL,
    START_DATE         DATETIME     NOT NULL,
    END_DATE           DATETIME     NOT NULL,
    USER_ID            VARCHAR(36)  NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

