package com.buildit.bookit.database.ddl

val createBookableTable = "CREATE TABLE BOOKABLE (BOOKABLE_ID INTEGER, BOOKABLE_NAME VARCHAR(50), BOOKABLE_STATUS CHAR(1))"
val insertRedBookable = "INSERT INTO BOOKABLE(BOOKABLE_ID, BOOKABLE_NAME, BOOKABLE_STATUS) VALUES (1, 'Red', 'N')"

val createLocationTable = "CREATE TABLE LOCATION (LOCATION_ID INTEGER, LOCATION_NAME VARCHAR(50), LOCATION_TZ VARCHAR(50))"
val insertNYCLocation = "INSERT INTO LOCATION(LOCATION_ID, LOCATION_NAME, LOCATION_TZ) VALUES(1, 'NYC', 'America/NewYork')"
val insertLondonLocation = "INSERT INTO LOCATION(LOCATION_ID, LOCATION_NAME, LOCATION_TZ) VALUES(2, 'LON', 'Europe/London')"

val createBookingTable = "CREATE TABLE BOOKING (BOOKING_ID INTEGER, BOOKABLE_ID INTEGER, SUBJECT VARCHAR(255), START_DATE TIMESTAMP, END_DATE TIMESTAMP)"
